language: php

php:
  - 7.0
  - 7.1

env:
  matrix:
    - TYPO3_VERSION=8.7.0
    - TYPO3_VERSION=8.7.1
    - TYPO3_VERSION=8.7.2
    - TYPO3_VERSION=8.7.3
    - TYPO3_VERSION=8.7.4
    - TYPO3_VERSION=8.7.*

sudo: false

addons:
  code_climate:
    repo_token:
      secure: kHpQ5koZ1E53TkaEmok/N0n7EyHBvdQu6hwLgEwmhPgKl4TylzHVqHwVfhodnQamwDy6V+5s/acBH8oPbQ3PkwUg7N3xpa19xE/ixkcWfF26O6ZxrJ+AbAOrF9QsG4Kor9KbTmKJQvn7RJ6PUTe59G0jxWildX175lcXPoqk7vh/iTgRk0SbFApyrBYcbnjh/sJNimsyYKa3t4qQE1KlgvH5OpNtY55i7pRPyb75ro1ZPh9GGzZxFvilZKZ9TEY/rjNhyifvAe48d6w9vQb8907diXmvsyMLljs/b4USNRIeCCH3gxyx2qWBjJDj9iUvCLhK5+Bl3eTrqAmovWHC14TcR0zUt8nKvApHprI2tqxwkC5J38gY208pmVgTnuIErF9mAQK1wYAleKW8JBcXM12FQTARJ/RivVq/zVAiNfKXRGFcCyaaxB294fhT4v1OiaqngO7b1jNviDlz9UjnpuYrL4g53fyVIFvcBp0JP8sOI/x5oUiB9bHQj0S28+wmxpIcyFk9aL5YXhvLs04Yju18pGGUjg7ruyTnULtUAun+iohwCDuLnPlzj0x7NcKK5LJBok4EakLPWY1xvHPF45Pu9FJEdXvwTIjsEJPvXku8kDpJJgtIGUmsTAs8/48FiTh/eSk6Nz8EcmKhgO5mRn9vfarSWfD2qBD4BkC+F6c=

  apt:
    packages:
      - parallel
      - imagemagick

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  - cd .Build
  - mkdir -p build/logs/
  - mkdir -p coverage/
  - composer require typo3/cms=$TYPO3_VERSION
  - export TYPO3_PATH_WEB=$TRAVIS_BUILD_DIR/.Build/web;
  - cd $TRAVIS_BUILD_DIR

script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} \;
  - >
    echo;
    echo "Running unit tests";
    php .Build/bin/phpunit --colors --coverage-php=.Build/coverage/unit.cov --configuration .Build/UnitTests.xml;
  - >
    echo;
    echo "Running functional tests";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseName="typo3";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    export PROCESSOR="ImageMagick";
    export PROCESSOR_PATH="/usr/bin/";
    export PROCESSOR_PATH_LZW="/usr/bin/";
    php .Build/bin/phpunit --process-isolation --colors --coverage-php=.Build/coverage/functional.cov --configuration .Build/FunctionalTests.xml;

after_script:
  - cd .Build
  - php bin/phpcov merge coverage --clover build/logs/clover.xml
  - php bin/test-reporter
